import tkinter as tk
from tkinter import filedialog, ttk
import re
import os
import requests
import textwrap

# --- Configuration ---
TAILWIND_CDN_URL = "https://cdn.tailwindcss.com/3.4.17"
# This regex matches class attributes (class="..." or className="...")
# and extracts the space-separated class names.
CLASS_EXTRACTION_REGEX = re.compile(
    r'(?:class|className)\s*=\s*["\']([^"\']+)["\']',
    re.DOTALL
)

def perform_css_operation(input_filepath, output_dir, source_css_path=None, full_download=False):
    """
    Performs CSS extraction (purging) or full download based on flags.
    """
    try:
        # 1. Get Full CSS Content (Local File or CDN)
        source_info = TAILWIND_CDN_URL
        if source_css_path and os.path.exists(source_css_path):
            try:
                # Read from local file
                with open(source_css_path, 'r', encoding='utf-8') as f:
                    full_css_content = f.read()
                source_info = os.path.basename(source_css_path)
            except Exception as e:
                return 0, f"Error reading local CSS source file: {e}"
        else:
            # Fallback to CDN fetch
            response = requests.get(TAILWIND_CDN_URL, timeout=15) # Increased timeout
            response.raise_for_status()
            full_css_content = response.text
        
        # --- Full Download Mode (Guaranteed method for offline use) ---
        if full_download:
            # 5. Write Full CSS to Output File
            output_filename = "full_tailwind_source.css"
            output_filepath = os.path.join(output_dir, output_filename)

            final_css = textwrap.dedent(f"""
            /*
            * Generated by Tailwind Utility Extractor (Full Download Mode)
            * Source: {source_info}
            * NOTE: This file contains ALL Tailwind CSS rules and is suitable for offline development.
            * It is NOT purged/minified for production use.
            */

            {full_css_content}
            """)

            with open(output_filepath, 'w', encoding='utf-8') as f:
                f.write(final_css.strip())

            return len(full_css_content), f"Successfully downloaded FULL CSS source ({len(full_css_content)} bytes) to: {output_filepath}"


        # --- Purging Mode (Original logic, remains a fragile process) ---
        
        # 1. Read Input File (where classes are used)
        with open(input_filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        # 2. Extract Unique Class Names
        raw_class_strings = CLASS_EXTRACTION_REGEX.findall(content)
        unique_classes = set()
        for class_string in raw_class_strings:
            # Split by space and filter out empty strings
            classes = [c.strip() for c in class_string.split() if c.strip()]
            unique_classes.update(classes)

        if not unique_classes:
            return 0, "No CSS classes found in the input file for purging."
            
        # 4. Search and Extract Matching CSS Rules
        extracted_css_rules = []
        extracted_count = 0
        
        # WARNING: Regex parsing of minified CSS is inherently fragile.
        
        for class_name in unique_classes:
            # Create a selector string to search for. Must handle CSS escapes.
            css_selector = "." + class_name.replace(":", r"\:").replace("/", r"\/").replace("[", r"\[").replace("]", r"\]").replace("(", r"\(").replace(")", r"\)")
            
            # Find the *start* of the rule definition:
            start_index = full_css_content.find(css_selector)
            
            if start_index != -1:
                # Use a block-matching regex to capture the rule body { ... }
                rule_match = re.search(
                    re.escape(css_selector) + r'(\{.*?\}|\{.*?\{.*?\}\})', 
                    full_css_content, 
                    re.DOTALL
                )
                
                if rule_match:
                    full_rule = rule_match.group(0)
                    
                    # --- Media Query & Nested Rule Handling ---
                    media_start_index = full_css_content.rfind('@media', 0, rule_match.start())
                    
                    if media_start_index != -1:
                        media_brace_start = full_css_content.find('{', media_start_index)
                        
                        brace_count = 1
                        current_pos = media_brace_start + 1
                        media_rule_end = -1
                        while current_pos < len(full_css_content):
                            char = full_css_content[current_pos]
                            if char == '{':
                                brace_count += 1
                            elif char == '}':
                                brace_count -= 1
                                if brace_count == 0:
                                    media_rule_end = current_pos
                                    break
                            current_pos += 1
                        
                        if media_rule_end != -1:
                            extracted_rule = full_css_content[media_start_index:media_rule_end + 1]
                            if extracted_rule not in extracted_css_rules:
                                extracted_css_rules.append(extracted_rule)
                                extracted_count += 1
                                continue

                    if full_rule not in extracted_css_rules:
                        extracted_css_rules.append(full_rule)
                        extracted_count += 1
            
        # 5. Write to Output File
        output_filename = "purged_tailwind.css" # Renamed output file for clarity
        output_filepath = os.path.join(output_dir, output_filename)

        final_css = textwrap.dedent(f"""
        /*
        * Generated by Tailwind Utility Extractor (Purge Mode)
        * Extracted {extracted_count} utility rules from source: {source_info}
        * Input file (classes used in): {os.path.basename(input_filepath)}
        * WARNING: Extraction relied on fragile regex matching of minified CSS and may be incomplete.
        */

        {os.linesep.join(extracted_css_rules)}
        """)

        with open(output_filepath, 'w', encoding='utf-8') as f:
            f.write(final_css.strip())

        return extracted_count, f"Successfully extracted {extracted_count} rules to: {output_filepath}"

    except requests.exceptions.RequestException as e:
        return 0, f"Error fetching CSS source: Check internet connection or URL. Details: {e}"
    except FileNotFoundError:
        return 0, "Input file (Step 1) not found."
    except Exception as e:
        return 0, f"An unexpected error occurred: {e}"

class TailwindPurgerApp:
    """Tkinter GUI for the Tailwind CSS Extractor."""

    def __init__(self, master):
        self.master = master
        master.title("Tailwind Utility Purger")
        master.geometry("600x520") # Increased height for new field and checkbox
        master.configure(bg="#2c3e50") # Dark theme background

        self.input_file_path = tk.StringVar()
        self.output_dir_path = tk.StringVar()
        self.source_css_file_path = tk.StringVar() # Variable for local CSS source
        self.download_full_css = tk.BooleanVar(value=False) # NEW: Boolean variable for full download
        
        # Set default output path to user's home directory or current working directory
        try:
            default_dir = os.path.expanduser("~")
        except:
            default_dir = os.getcwd()
            
        self.output_dir_path.set(default_dir)

        # Apply a custom style for a modern look
        self.style = ttk.Style()
        self.style.theme_use('clam')
        self.style.configure('TFrame', background='#34495e', borderwidth=0)
        self.style.configure('TLabel', background='#34495e', foreground='white', font=('Inter', 10))
        self.style.configure('TButton', background='#16a085', foreground='white', font=('Inter', 10, 'bold'), borderwidth=0, relief='flat')
        self.style.map('TButton', background=[('active', '#1abc9c')])
        self.style.configure('TEntry', fieldbackground='#ecf0f1', foreground='#2c3e50', borderwidth=1, relief='flat')

        # Main frame
        main_frame = ttk.Frame(master, padding="20 20 20 20")
        main_frame.pack(fill='both', expand=True, padx=10, pady=10)

        # Title
        title_label = ttk.Label(main_frame, text="Tailwind Utility Extractor", font=('Inter', 18, 'bold'), foreground='#1abc9c')
        title_label.pack(pady=(0, 20))

        # --- 1. Input File Selection (Markup) ---
        ttk.Label(main_frame, text="1. Input File (HTML/JS - where classes are used) *Required for Purging* :").pack(anchor='w', pady=(10, 5))
        
        input_frame = ttk.Frame(main_frame)
        input_frame.pack(fill='x')

        self.input_entry = ttk.Entry(input_frame, textvariable=self.input_file_path, width=50)
        self.input_entry.pack(side='left', fill='x', expand=True, padx=(0, 5))

        input_button = ttk.Button(input_frame, text="Browse", command=self.browse_input)
        input_button.pack(side='right')
        
        # --- 2. Source CSS File Selection (Optional) ---
        ttk.Label(main_frame, text="2. Source CSS File (Optional - your centralized CSS file or leave empty for CDN):").pack(anchor='w', pady=(10, 5))
        
        css_source_frame = ttk.Frame(main_frame)
        css_source_frame.pack(fill='x')

        self.css_source_entry = ttk.Entry(css_source_frame, textvariable=self.source_css_file_path, width=50)
        self.css_source_entry.pack(side='left', fill='x', expand=True, padx=(0, 5))

        css_source_button = ttk.Button(css_source_frame, text="Browse", command=self.browse_css_source)
        css_source_button.pack(side='right')

        ttk.Label(main_frame, text=f"If left empty, the tool will fetch the source CSS from the CDN: {TAILWIND_CDN_URL}", font=('Inter', 8, 'italic'), foreground='#95a5a6').pack(anchor='w', pady=(0, 10))

        # --- 3. Output Directory Selection ---
        ttk.Label(main_frame, text="3. Output Directory:").pack(anchor='w', pady=(10, 5))
        
        output_frame = ttk.Frame(main_frame)
        output_frame.pack(fill='x')

        self.output_entry = ttk.Entry(output_frame, textvariable=self.output_dir_path, width=50)
        self.output_entry.pack(side='left', fill='x', expand=True, padx=(0, 5))

        output_button = ttk.Button(output_frame, text="Browse", command=self.browse_output)
        output_button.pack(side='right')
        
        # --- New Checkbox for Full Download Mode ---
        full_download_check = ttk.Checkbutton(main_frame, 
                                              text="Download Full Source CSS (Bypasses purging, requires only Step 2 or CDN)", 
                                              variable=self.download_full_css)
        full_download_check.pack(anchor='w', pady=(10, 0))

        # --- Run Button ---
        run_button = ttk.Button(main_frame, text="Execute CSS Operation", command=self.run_extraction)
        run_button.pack(pady=30, ipadx=20, ipady=10)

        # --- Status Label ---
        self.status_label = ttk.Label(main_frame, text="Ready. Requires 'requests' library.", font=('Inter', 10, 'italic'), foreground='#bdc3c7')
        self.status_label.pack(fill='x', pady=(10, 0))

        # --- Info Label ---
        ttk.Label(main_frame, text=f"Note: Purging Mode (default) relies on fragile regex parsing and may be incomplete.", font=('Inter', 8), foreground='#95a5a6').pack(anchor='w', pady=(10, 0))

    def browse_input(self):
        """Opens file dialog for input file selection (markup)."""
        filetypes = [("Web Files", "*.html *.js *.jsx *.tsx *.vue"), ("All Files", "*.*")]
        filename = filedialog.askopenfilename(
            title="Select Input File (HTML/JS)",
            filetypes=filetypes
        )
        if filename:
            self.input_file_path.set(filename)

    def browse_css_source(self):
        """Opens file dialog for the local CSS source file."""
        filetypes = [("CSS Files", "*.css"), ("All Files", "*.*")]
        filename = filedialog.askopenfilename(
            title="Select Source CSS File",
            filetypes=filetypes
        )
        if filename:
            self.source_css_file_path.set(filename)

    def browse_output(self):
        """Opens directory dialog for output folder selection."""
        dirname = filedialog.askdirectory(title="Select Output Directory")
        if dirname:
            self.output_dir_path.set(dirname)

    def run_extraction(self):
        """Executes the CSS operation process and updates the GUI status."""
        input_file = self.input_file_path.get()
        output_dir = self.output_dir_path.get()
        source_css_file = self.source_css_file_path.get()
        full_download_mode = self.download_full_css.get()

        # Validation logic updated for Full Download Mode
        if not output_dir or not os.path.isdir(output_dir):
            self.update_status("Error: Please select a valid output directory (Step 3).", '#e74c3c')
            return
        
        if not full_download_mode and (not input_file or not os.path.exists(input_file)):
            self.update_status("Error: Please select a valid input file (Step 1) for purging.", '#e74c3c')
            return
        
        if source_css_file and not os.path.exists(source_css_file):
            self.update_status("Warning: Local source CSS file not found. Falling back to CDN.", '#f39c12')
            source_css_file = None 

        status_msg = "Processing... Fetching source content and performing operation."
        if full_download_mode:
            status_msg = "Processing... Downloading FULL CSS source."
            
        self.update_status(status_msg, '#f39c12')
        self.master.update()

        # Call the core logic, passing the new flag
        count, message = perform_css_operation(input_file, output_dir, source_css_file, full_download_mode)

        if count > 0:
            self.update_status(message, '#2ecc71')
        else:
            self.update_status(message, '#e74c3c')

    def update_status(self, message, color='#bdc3c7'):
        """Updates the status label with a message and color."""
        self.status_label.config(text=message, foreground=color)


if __name__ == "__main__":
    # Ensure necessary dependency is installed, otherwise prompt the user.
    try:
        import requests
    except ImportError:
        print("Error: The 'requests' library is required. Please install it with: pip install requests")
        exit()
        
    root = tk.Tk()
    app = TailwindPurgerApp(root)
    root.mainloop()
